### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by sanket-desai** [shz9/viprs#5]
When I try to run the test example given on the project page (specifically calling function "mgp.GWADataLoader"

gdl = mgp.GWADataLoader(bed_files=mgp.tgp_eur_data_path(), sumstats_files=mgp.ukb_height_fastGWA_path(), sumstats_format="fastGWA")

gives an error - AttributeError: module 'collections' has no attribute 'Iterable'

I am using python3.10 (22.04.1-Ubuntu) and installed viprs using pip as suggested in the manual.

**Comment by shz9** [comment]
Hey Sanket,

Thanks for reporting this issue. This bug is due to difference in python versions. I tested my code with `python3.7` and `python3.8`, where the `collections.Iterable` was defined. In newer versions of `python`, this is now defined under `collections.abc.Iterable`. That's why you're getting the error you describe.

I'm working on releasing a major update to `magenpy` and `viprs` that will fix this issue + many others bugs. But in the meantime, please try and see if the example would work with `python3.7` or `python3.8`.

Best,

Shadi

**Comment by shz9** [comment]
This issue should be fixed in latest version v0.1 of both `magenpy` and `viprs`.
