### ISSUE TITLE
FileNotFoundError(f"No valid LD matrix files were found at: {args.ld_dir}")

### ISSUE THREAD

**Issue by HUST-341** [shz9/viprs#11]
Hello,

I am encountering the following error when running VIPRS:```raise FileNotFoundError(f"No valid LD matrix files were found at: {args.ld_dir}")```. I am using `magenpy` version `0.1.4` and `viprs` version `0.1.1`. I successfully computed the LD using `magenpy` with the following command:
```python
magenpy_ld --estimator windowed --backend plink --temp-dir ~/temp --output-dir ~/UKB_LD_windowed --bfile ~/ukb_eur_chr22 --ld-window-kb 1000 --ld-window 100
```
However, when I attempt to run VIPRS, I encounter the error below:

```python
      **********************************************
                    _____
            ___   _____(_)________ ________________
            __ | / /__  / ___  __ \__  ___/__  ___/
            __ |/ / _  /  __  /_/ /_  /    _(__  )
            _____/  /_/   _  .___/ /_/     /____/
                          /_/
        Variational Inference of Polygenic Risk Scores
        Version: 0.1.1 | Release date: April 2024
        Author: Shadi Zabad, McGill University
        **********************************************
        < Fit VIPRS models to GWAS summary statistics >

---------------------  Parsed arguments  ---------------------

-- ld_dir : /data/UKB_LD_windowed/ld/chr_21
-- sumstats_path : /data/Height_test.fastGWA
-- output_dir : /data/temp/
-- temp_dir : /data/temp
-- sumstats_format : fastgwa
-- validation_bed : /data/ukb22828_eur_hm3_chr21
-- validation_pheno : /data/phen
-- validation_keep : /data/keep
-- hyp_search : GS
-- backend : plink
Traceback (most recent call last):
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 657, in <module>
    main()
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 595, in main
    check_args(args)
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 45, in check_args
    raise FileNotFoundError(f"No valid LD matrix files were found at: {args.ld_dir}")
FileNotFoundError: No valid LD matrix files were found at: /data/UKB_LD_windowed/ld/chr_21
```
Could you please advise on how to resolve this issue?

Additionally, I noticed that the section at [https://shz9.github.io/viprs/download_ld/](https://shz9.github.io/viprs/download_ld/) is currently empty. Would it be possible to add content to that section?

Thank you very much!

**Comment by shz9** [comment]
Hi, this issue is due to the version `viprs==0.1.1` being outdated and using wrong interface for loading LD data.
If you install `0.1.2` directly from GitHub, this issue should be resolved:

```
pip uninstall viprs -yy
pip install git+https://github.com/shz9/viprs.git
```

I'm working on releasing the new `0.1.2` to PyPI soon. Just doing some final rounds of testing. I will also release new LD matrices for download along with the new software version soon.

Thank you for your patience and understanding. Let me know if you still see any issues after installing from github.

**Comment by HUST-341** [comment]
Thank you for your previous response!

After installing version `0.1.2`, I was able to resolve the earlier issues. When using `hyp_search=EM`, I successfully obtained results. However, I encountered some problems when switching to `hyp_search=GS`.

The first error I encountered is as follows:

```python
File "/home/anaconda3/envs/py38/bin/viprs_fit", line 417, in fit_model
    grid.generate_pi_grid(n_steps=args.pi_steps)
TypeError: generate_pi_grid() got an unexpected keyword argument 'n_steps'，
```
It seems that the line `grid.generate_pi_grid(n_steps=args.pi_steps)` needs to be changed to `grid.generate_pi_grid(steps=args.pi_steps)` to resolve this issue.

However, even after making this modification, I am still facing issue:
```python
        **********************************************
                    _____
            ___   _____(_)________ ________________
            __ | / /__  / ___  __ \__  ___/__  ___/
            __ |/ / _  /  __  /_/ /_  /    _(__  )
            _____/  /_/   _  .___/ /_/     /____/
                          /_/
        Variational Inference of Polygenic Risk Scores
        Version: 0.1.2 | Release date: December 2024
        Author: Shadi Zabad, McGill University
        **********************************************
        < Fit VIPRS models to GWAS summary statistics >

---------------------  Parsed arguments  ---------------------

-- ld_dir : /data/UKB_LD_windowed/chr_21
-- sumstats_path : /data/Height_test.fastGWA
-- output_dir : /data/temp/
-- temp_dir : /data/temp
-- sumstats_format : fastgwa
-- validation_bed : /data/ukb22828_eur_hm3_chr21
-- validation_pheno : /data/phen
-- validation_keep : /data/keep
-- lambda_min : infer
-- hyp_search : GS
-- pi_steps : 10
-- sigma_epsilon_steps : 10
-- backend : plink

-------------  Reading & harmonizing input data  -------------

> Reading the training dataset...
> Reading LD metadata...
> Reading summary statistics...
Harmonizing data: 100%|████████████████████████████████████████| 22/22 [00:00<00:00, 46.01it/s]
> Reading the validation dataset...
> Reading genotype metadata...
> Reading phenotype file...

----------------------  Model details  -----------------------

- Model: VIPRS
- Hyperparameter tuning strategy: Grid search
- Model selection criterion: validation

------------------------  Inference  -------------------------

here?
Chromosome 21 (14681 variants): 100%|█| 36/36 [00:03<00:00, 10.43it/s, Best ELBO=-2265743.0000,
Traceback (most recent call last):
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 757, in <module>
    main()
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 704, in main
    fit_results = Parallel(n_jobs=args.n_jobs)(
  File "/home/anaconda3/envs/py38/lib/python3.8/site-packages/joblib/parallel.py", line1918, in __call__
    return output if self.return_generator else list(output)
  File "/home/anaconda3/envs/py38/lib/python3.8/site-packages/joblib/parallel.py", line1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/anaconda3/envs/py38/bin/viprs_fit", line 464, in fit_model
    m = m.select_best_model(data_dict['valid'], criterion=args.grid_metric)
KeyError: 'valid'
```
Firstly, I am not quite clear on the meaning of "here?"

Additionally, I encountered a `KeyError: 'valid'`. Since I provided `args.validation_bed`, there is no assignment for `data_loaders[c]['valid']` in the if-else statement at line 213 of the `viprs_fit` file. I attempted to assign a value, but it led to more issues. I hope to find a solution for this problem.

I greatly appreciate your work and hope to see the final version soon!

**Comment by shz9** [comment]
Hi,

Thank you for reporting these issues. I encountered some of them before and was working on addressing them. I just pushed the latest version of the software to GitHub. I believe this should address most of these issues.

Do you mind trying the latest version with `GS` and letting me know how it goes?

Regarding the `here?` print statement, this was a leftover from earlier debugging attempts. I removed it in the latest version.

**Comment by shz9** [comment]
Any updates on this? 

Btw, the latest version (`v0.1.2`) is now on PyPI and you should be able to install it as follows: 

```
pip install viprs --upgrade
```

I believe these issues should be resolved in the new release. If the problems persist or you find other issues, feel free to open another issue.
